name: AntiTotemGhost
main: net.opmasterleo.AntiTotemGhost.AntiTotemGhost
author: OPmasterLEO
version: "${version}"
api-version: "1.21"
description: "${description}"
folia-supported: true

commands:
  AntiTotemGhost:
    description: AntiTotemGhost admin command
    usage: /AntiTotemGhost [reload|debug|stats|compat]
    permission: AntiTotemGhost.admin
    aliases: [mag, antighost]

permissions:
  AntiTotemGhost.admin:
    description: Admin permission for AntiTotemGhost
    default: op
